#ui config

browser=chrome
baseUrl=https://automationexercise.com
implicitWait=10
pageLoadTimeout=30
headless=false
environment=dev

#api config

apiBaseUrl=https://restful-booker.herokuapp.com
apiUsername=admin
apiPassword=password123