name: Selenium Framework CI

on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    name: Smoke - ${{ matrix.browser }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [ chrome, firefox ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Run Smoke Tests
        run: mvn test -Psmoke -Dbrowser=${{ matrix.browser }} -Dheadless=true